version: "3.7"

services:
  macfront:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: macfront
    restart: always
    ports:
      - "8080:8080"
    networks:
      - vue-network
networks:
  vue-network:
    driver: bridge