version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./macmasterfrontend-vue-app-1:/app
    ports:
      - 8081:80
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8081:80
    depends_on:
      - frontend